### ISSUE TITLE
Saves

### ISSUE THREAD

**Issue by ChakornK** [lemons-studios/Mission-Monkey#11]
Self-Explanatory. Manual saves are required, Auto-saves are not needed

**Comment by Shob3r** [comment]
I am looking into how saves can be integrated with the game starting now

**Comment by Shob3r** [comment]
Pushing back to 0.4.0 again

**Comment by Shob3r** [comment]
the oldest feature that I have wanted to implement is being implemented soon and it's getting real

**Comment by Shob3r** [comment]
Work will commence on this soon

**Comment by Shob3r** [comment]
it is being worked on

**Comment by Shob3r** [comment]
The actual save system code is done, but it now needs to remember if story events have been triggered or not and what the player has done in each scene, etc etc. not gonna be fun manually writing every single event like this out in the future, praying that there is an easier way (there probably is and I'm just a bad programmer)

**Comment by Shob3r** [comment]
It's done for now. I might create a separate issue for checking if story events are triggered once the player loads into the respective scene
